name: saetest
version: 1

handle:
- rewrite: if (path ~ "^(?!codeigniter/)(.*)") goto "codeigniter/$1?%{QUERY_STRING}"
- rewrite: if (!-d && !-f) goto "codeigniter/index.php/$1?%{QUERY_STRING}"
- compress: if(in_header["Accept-Encoding"] ~ "gzip") compress