name: saetest
version: 1

handle:
- rewrite:if (path ~ "^(?!codeigniter/)(.*)") goto "codeigniter/$1?%{QUERY_STRING}"
#- rewrite:if (in_header["host"] ~ "nanjinghuluanpao.sinaapp.com" && path ~ "^(?!codeigniter/)(.*)") goto "codeigniter/$1?%{QUERY_STRING}"